### ISSUE TITLE
Old or new

### ISSUE THREAD

**Issue by dancinglightning** [gollum/gollum_rails#1]
I would say i push what i have as master.

Then we can work on it until ready

And then release as the new gem, version 2.0

Ok ??

PS , I have the edit page up and am trying to understand authentication

**Comment by nirnanaaa** [comment]
Just mailed you. I am not so sure about working from master as there are several bugs (I started with gollum back in the days where it was not seperated from gollum-lib, with version 0.0.1 or so...). It could be more stable to start it over.

**Comment by dancinglightning** [comment]
Fine, let's do that. Or more precisely: since you seem more busy, let me do that.
with the redmine views and controllers i may as well start from a new app.

btw: I think since we don't have a mailing list, creating issues for open questions is good communication.
better to track than emails. ok ? 
That may result in a fair amount of open issues in the beginning but it separates them nicely.

If this is ok, do close this issue

**Comment by nirnanaaa** [comment]
This is an excelent idea. We could create some labels to identify them, couldn't we?

**Comment by nirnanaaa** [comment]
This week is actually better with my time. I could work on some (not that much) code today.

**Comment by dancinglightning** [comment]
good. Let's skype today then finally. maybe even now, since you seem online too. 

Does that mean you want to make that fresh start ? or shall i and then we split tasks ?

**Comment by nirnanaaa** [comment]
I am on my way home in a few minutes how about 16:45? (my time)

**Comment by dancinglightning** [comment]
that's in about an hour yes ?
fine by me, i'm just sitting here

**Comment by dometto** [comment]
If you're using issues to communicate, I'm going to unwatch this repo for now (lots of e-mails). :) Feel free to @-mention me if you have any questions!

**Comment by nirnanaaa** [comment]
I am online. Finally :smile:

**Comment by dancinglightning** [comment]
ok, time to go to bed.

very very basic. but i won't have time tomorrow. New was definitely the longer road.

go to test_app and run rails s
but bundle in main dir
will fix that when i start with testing
