### ISSUE TITLE
Adapter, use rugged

### ISSUE THREAD

**Issue by dancinglightning** [gollum/gollum_rails#10]
i've read about the adapters a little now and they say rugged is the way to go. 
Should we just go ahead and use that?
Sounds solid enough but lets see what they say on the list.

ps: sorry i didn't get that fully when you asked (though my answer is probably still true). But one of the first gollum experiences for me was the grit-adapter having some ancient dependency and if it is not well maintained i'd rather use the other.

**Comment by nirnanaaa** [comment]
I think we should go for the rugged adapter. I made a few tests a couple of months back and rugged was the clear winner in terms of speed and functionality (automatic cloning etc...)

**Comment by dancinglightning** [comment]
ok, that is settled. 
I'll say on the list that we "beta-test"
