### ISSUE TITLE
Stepping back from Development

### ISSUE THREAD

**Issue by nirnanaaa** [gollum/gollum_rails#12]
Hey guys,

I am sorry but I have to inform you that I will step back from developing gollum_rails any further. 

There are a few reasons for my decision:

1) I have absolutely no time left due to several high level projects at work and in my personal live. 

2) my bosses have thought about gollum and the whole effort I have put into implementing it into our infrastructure. They decided, that our internal redmine (which was powered by my implementation of gollum_rails and gollum_redmine) will be discontinued as of 1th of March 2015. This also means that gollum will not run at our company anymore. Furthermore this means I cannot work on developing gollum_rails at work anymore. 

I am sorry about this decision, but it is the only option for not burning out completely. Hope this Project grows and grows on. :smile: @dancinglightning @dometto 

Cheers,

nirnanaaa

**Comment by dancinglightning** [comment]
That is a shame, it was nice to work together while it lasted.

I guess you have pushed everything you have.
You can transfer ownership to me if you have't yet http://guides.rubygems.org/command-reference/#gem-owner
I will continue, but like i said am going on a 7 week holiday quite soon.
You should also put up a notice on your website of this situation.

So i wish you less stress 
Torsten

**Comment by nirnanaaa** [comment]
Just added you as gem owner. Thanks for taking care ;) https://rubygems.org/gems/gollum_rails

**Comment by dometto** [comment]
Sorry to hear that, @nirnanaaa! Good luck with all the busy-ness and thanks for helping to move the project over to the gollum org.

@dancinglightning, I hope you'll be able to continue work on this. If you need any gollum-related help feel free to sends us an e-mail on the dev-list.

**Comment by dancinglightning** [comment]
@dometto did you see i on the list, i already asked for some help with the model layer.
I did an outline here https://github.com/gollum/gollum_rails/issues/9

**Comment by bartkamphorst** [comment]
@nirnanaaa Sorry to see you go. All the best in your endeavors!
