### ISSUE TITLE
GollumRails::Persistance::AttributeMissingError

### ISSUE THREAD

**Issue by ltap** [gollum/gollum_rails#15]
Hi,
I am trying to use gollum rails on OpenShift,
When I try to create a page, I get the following error:
```
Started POST "/pages/"

Processing by WikiController#create_page as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"abcdedf","name"=>"name", "content"=>"content", "commit"=>"submit"}

Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.5ms)

GollumRails::Persistance::AttributeMissingError (Attributes are missing. Error message: <undefined method `put_raw_object' for nil:NilClass>):

```

The line that produce the error is this (the name and content etc are fetched from the params hash, and I made sure they are all present):
```
@page=Page.create(name: "name", content:"content",format: :markdown, commit: { name: "committer", email: "email", message: "created new page"})
```
What could be the cause of this error? I read on the gollum rails code that it may have something to do with missing an attribute, and there was an attribute path that is supposed to be automatically set in the initializer/setup? Could it be the cause? I need to urgently solve this issue, so any help would be greatly appreciated. Thank you! :)

**Comment by dancinglightning** [comment]
Hi @ltap 
Nice you're trying to use it, it has been somewhat dormant.
Your error description is somewhat thin regarding your setup, so it's difficult to tell.
Ideally you could write a failing test case :-)

My best guess is: are you using your own form and have the post url wrong ?
Since it's not ActiveRecord it is slightly different, look at the templates, they have tests and were working.

Torsten

**Comment by ltap** [comment]
Hi @dancinglightning,
Thank you for the quick reply!
Yes I am using my own form. It maps to a controller action where the Page is getting created,
```
@page=Page.create(name: "name", content:"content",format: :markdown, commit: { name: "committer", email: "email", message: "created new page"})
```
I have checked that all the params are passed correctly. I am think this has something to do with my setup on OpenShift too, as the code is working properly locally.
It is just strange that I got the error
```
GollumRails::Persistance::AttributeMissingError (Attributes are missing. Error message: <undefined method `put_raw_object' for nil:NilClass>):
```
Since none of my attributes seemed to be missing. 

Thanks again!

**Comment by dancinglightning** [comment]
Especially since ::persistance is not a module. Looks like reflected (possibly AR) code

check the url you post to, should be new_wiki_page_path

**Comment by rwwaskk** [comment]
Hey I am having the same problem.
And I am a bit confused as what guides to look at. 
I was looking at https://github.com/nirnanaaa/gollum_rails/wiki/Usage
However in this repo the method calls seems to be a bit different?

**Comment by dancinglightning** [comment]
This repo is a complete rewrite from nirnanaa's , they only share the name.

If you specify your problem, even write a testcase, i can try to help.
Are you using new_wiki_page_path?

It is not completely standardized rails as it is not an AR model (though pulls are welcome)

**Comment by dancinglightning** [comment]
@ltap @rwwaskk 
I updated the README and fixed several minor issues.
Please re-read (especially the part about engines and mounting) and follow instructions.
I did so myself and it works for me.

Would be great to get your setup to work too.

Please create new issues if there are questions.
