### ISSUE TITLE
Haml + sass

### ISSUE THREAD

**Issue by dancinglightning** [gollum/gollum_rails#2]
I am used to working with haml (and sass). I find them much cleaner and soo much easier to read.

Since we're starting new, i propose to use haml.

**Comment by nirnanaaa** [comment]
I used haml for a couple of projects and sass(Scss) for even more so there shouldn't be any problem. Should we force the user to use the asset pipeline or should we provide a generator to the user to move them to public?

**Comment by dancinglightning** [comment]
Definitely asset pipeline. It is one of the very good features of rails.

I don't know how you would do caching and be able to change assets without.

**Comment by dancinglightning** [comment]
btw, are you good at css / styling. 

Should we use a framework? I only know bootstrap.

**Comment by nirnanaaa** [comment]
I can do the styling... If I have time. Otherwise we could use bootstrap or foundation to start with (I favor bootstrap).

**Comment by dometto** [comment]
Gollum's own styling is just being migrated to sass (https://github.com/gollum/gollum/issues/917). Wouldn't it be best to use the same assets as gollum itself as much as possible? Otherwise we'd have to maintain two distinct sets of assets.

**Comment by dancinglightning** [comment]
That is an interesting proposal.

I just would not be sure how to. For one it would have to be in it's own gem or in the -lib (i think?).
Or gollum_rails would be dependent on gollum, not gollum-lib, which i find a little strange.

I could probably bend the rail asset paths. Meaning i assume sinatra has different directory structure.
And then i read there that you maybe using an asset pipeline, interesting.

We can try, maybe once you guys are stable with your sass.

**Comment by dometto** [comment]
I was thinking we could maybe do something clever with a git submodule. Yes, you should probably go ahead while the SASS changes are being carried out. But maybe it's good not to invest too much time in the styling til we're clear on which direction to take this.

**Comment by dancinglightning** [comment]
Yes a submodule could work.

I am surely not the man to go overboard with style :-)

Dawa Ometto wrote:
