### ISSUE TITLE
Implement travis to test repository.

### ISSUE THREAD

**Issue by nirnanaaa** [gollum/gollum_rails#3]
We should go for travis do all the testing. Any arguments?

**Comment by dancinglightning** [comment]
No, that is a good idea for continuos integration.

Off course it doesn't say how to test. I'm for rspec and can set that up for the engine, ok ?

btw: i've also started to use codeclimate, which does a nice overview of code "cleanliness" and also integrates with travis to gice you coverage percentage and a per line view. https://codeclimate.com/github/rubyclerks/office_clerk/BasketsController

**Comment by nirnanaaa** [comment]
Rspec looks good as i am also using it.

**Comment by nirnanaaa** [comment]
Travis is working now but it does not detect specs, need to fix that.

**Comment by dancinglightning** [comment]
Ok, well done (and the other stuff). I've added the first feature spec too so i thin k we can close this issue now and just get on with it.
