### ISSUE TITLE
Clean Documentation

### ISSUE THREAD

**Issue by nirnanaaa** [gollum/gollum_rails#4]
Create a clean documentation for installation / usage and publicity. Could possibly be a github.io page?

**Comment by nirnanaaa** [comment]
GitHub Pages should include some demo-videos and a step-by-step guide of how to install it

**Comment by dancinglightning** [comment]
ok. i pushed, maybe you can do a basic gh-pages branch
i'll mail when it's safe to make changes on the master branch, maybe thursday

**Comment by nirnanaaa** [comment]
you should pull first. I have updated the readme and gemspec a couple of times. Sorry.

**Comment by dancinglightning** [comment]
No problem. quicker push wins is what i say.

**Comment by dancinglightning** [comment]
I added a gemfile readme and gitignore to the gh pages

I don't think one needs to push the _site , it gets created automatically on the gh server

**Comment by nirnanaaa** [comment]
I am currently re-working the whole branch for layouting. This was just an initial jekyll import

**Comment by dancinglightning** [comment]
nice, try removing the _site folder. I don't have it in other projects.

**Comment by dancinglightning** [comment]
still an issue, but not sure about gh-pages anymore
