### ISSUE TITLE
Minor spelling fixes

### ISSUE THREAD

**Issue by sunny** [gollum/gollum_rails#7]
FYI, Just so you are notified that I touched the README. https://github.com/gollum/gollum_rails/commit/a7f9847885c702a0b2a9e7862e1b074cecec1516

Keep up the good work!

**Comment by dancinglightning** [comment]
Thanks. I often get that extra in in there for some reason.

btw: how can we ask question about the lib part. For suggestions or bugs 
we can use the tracker, nut just to ask ?

Sunny Ripert wrote:

**Comment by dometto** [comment]
@dancinglightning I think maybe opening up a gollum-dev mailinglist would not be a bad idea, also to enable [reporting of vulnerabilities](https://github.com/gollum/gollum-lib/issues/120). Google code provides free mailinglist services. Probably not everyone currently listed as an owner/contributer would want to be on there, but I wouldn't mind (although 1-to-1 communication should be off-list to ensure we don't spam each other).

**Comment by nirnanaaa** [comment]
have a look at https://groups.google.com/forum/#!forum/gollum-dev/new should be what you wanted?

**Comment by dometto** [comment]
:+1: I invited @bartkamphorst and @sunny. I haven't heard from @jamieoliver for a while, but anyone who wants to be on there can send their preferred e-mail address to the group owners via the google group page.
