### ISSUE TITLE
Flat vs Tree-Level

### ISSUE THREAD

**Issue by nirnanaaa** [gollum/gollum_rails#8]
Should we aim for a flat wiki (like gollum, github, wikipedia) or should we use kind of a tree view like a filesystem structure @dancinglightning

**Comment by dancinglightning** [comment]
I think a wiki is almost defined by not having structure. Just like it doesn't use html. One could look that up though, but i think it is the general expectation. 

The usual way is just to use underscores and longer and longer names if needed. Even wikipadia with millions of pages only has no structure (per language)

If you (or your bosses) **need** it, we should make it configurable.

**Comment by dancinglightning** [comment]
i had another idea about this. I still think we should not do folders. But for your app, you could simulate them by some other means. Ie a yaml file of the tree and some association to each file.

**Comment by nirnanaaa** [comment]
We thought about it and discussed that we, actually, do not need trees, but need to re-organize our stuff. Loads of work :sweat_smile:
